version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.2
workflows:
  deploy:
    jobs:
      - aws-deploy:
          filters:
            branches:
              only:
                - dev
                - master
          context: AWS

jobs:
  aws-deploy:
    docker:
      - image: "cimg/base:stable"
    executor: aws-cli/default
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run:
          command: npm install
          name: Install Node_Modules
      - run:
          command: npm run build
          name: Build Project
      - aws-cli/setup
      - run:
          command: aws s3 sync dist/ s3://slowsaver.com/$CIRCLE_BRANCH
          name: Deploy AWS S3
